//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom18_TTCM_CNTTVA1_K61.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public string IDcontent { get; set; }
        public string Namecontent { get; set; }
        public string Content { get; set; }
        public string Imagecontent { get; set; }
        public string Descrition { get; set; }
        public string Content2 { get; set; }
    }
}
