//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom18_TTCM_CNTTVA1_K61.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Idproduct { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string IDcategory { get; set; }
        public string Description { get; set; }
        public string IDtools { get; set; }
        public string IDtrademark { get; set; }
        public string Instruct { get; set; }
        public string ImageTool { get; set; }
    }
}
